title:            魅影绝代
description:      网站的描述内容。
copyright:        Lee
url: # 添加自定义网站url (格式: https://example.com)


future:      false  # 发布过时的帖子 --  true, false (默认)
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

permalink: /:title

# 显示在首页上的帖子数量
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  enable_coderay: false

include:
  - .htaccess

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp