# Site settings
title: 博客 | 记录一些东西...
description: "网站详细描述内容"
url: "https://www.artlee.cn"
author:
  name: "Lee"
  email: "hey@artlee.cn"
  url: "https://www.artlee.cn"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
