# 网站设置
title: 博客 | 记录一些东西...
description: "网站详细描述内容"
url: "https://www.artlee.cn"
author:
  name: "Lee"
  email: "hey@artlee.cn"
  url: "https://www.artlee.cn"

# 部署设置
baseurl:  # 将其更改为相对路径（例如：/blog/），或者只保留一个 “/”
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/


# 默认值
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# 插件
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-admin

# 自定义变量
version: "1.0.0"

# 选项
custom_header: false
custom_nav_footer: false
reverse: false
